### ISSUE TITLE
when preparing for shutdown, commands should fail but be able to view in history

### ISSUE THREAD

**Issue by oshai** [codeine-cd/codeine#106]

**Comment by oshai** [comment]
this is the current exception in the log:
2015-02-03 09:34:27,509 [qtp1168924571-22522] [AbstractServlet] WARN Error in servlet
codeine.utils.exceptions.InShutdownException
        at codeine.command_peer.NodesCommandExecuterProvider.createExecutor(NodesCommandExecuterProvider.java:39)
        at codeine.servlets.api_servlets.NodesCommandApiServlet.myPost(NodesCommandApiServlet.java:76)
        at codeine.servlet.AbstractServlet.doPost(AbstractServlet.java:84)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
        at codeine.CodeineWebServerBootstrap$1.handle(CodeineWebServerBootstrap.java:157)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
